name: Deploy to UnoEuro

on:
  push:
    branches:
      - main  # main branch'e push edilince çalışır

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Değişen dosyaları tespit için

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}
          server-dir: ${{ secrets.FTP_PATH }}
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            conn.php
            .env